import Header from '@/components/layout/Header';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex flex-col min-h-screen bg-gradient-to-b from-slate-900 via-purple-900 to-slate-900">
          <Header />

          <main className="flex flex-1">{children}</main>

          {/* Footer */}
          <footer className="flex justify-center gap-2 py-6 w-full items-center px-4 md:px-6 border-t border-purple-500/30 bg-black/40">
            <p className="text-sm text-gray-400">
              © {new Date().getFullYear()} Round Strike. All rights reserved.
            </p>
          </footer>
        </div>
      </body>
    </html>
  );
}
