import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Image from 'next/image';
import Link from 'next/link';
import MainLogo from '../../public/main-logo.png';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex flex-col min-h-screen bg-gradient-to-b from-slate-900 via-purple-900 to-slate-900">
          {/* Header */}
          <header className="px-4 lg:px-6 h-16 flex items-center backdrop-blur-sm bg-black/20 border-b border-purple-500/20">
            <Link
              href="/"
              className="flex items-center justify-center"
            >
              <div className="flex items-center space-x-2">
                <Image
                  src={MainLogo}
                  alt="Round Strike Logo"
                  className="w-12 h-12 rounded-full"
                />
                <span className="text-2xl font-bold text-white">Round Strike</span>
              </div>
            </Link>
            <nav className="ml-auto flex gap-4 sm:gap-6">
              <Link
                href="/register"
                className="text-sm font-medium text-gray-300 hover:text-white transition-colors"
              >
                Create account
              </Link>
              <Link
                href="/login"
                className="text-sm font-medium text-gray-300 hover:text-white transition-colors"
              >
                Login
              </Link>
            </nav>
          </header>

          <main className="flex flex-1">{children}</main>

          {/* Footer */}
          <footer className="flex justify-center gap-2 py-6 w-full items-center px-4 md:px-6 border-t border-purple-500/30 bg-black/40">
            <p className="text-sm text-gray-400">
              © {new Date().getFullYear()} Round Strike. All rights reserved.
            </p>
          </footer>
        </div>
      </body>
    </html>
  );
}
