services:
  backend:
    build:
      context: ./backend
    container_name: round-strike-backend
    volumes:
      - ./backend:/app
    ports:
      - "3002:3002"
    environment:
      - DB_USER=root
      - DB_PASS=root
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=roundstrike_db
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: round-strike-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: roundstrike_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
