services:
  backend:
    build:
      context: ./backend
    container_name: round-strike-backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./backend/.env:/app/.env
      - ./backend/.air.toml:/app/.air.toml
    ports:
      - "3002:3002"
    environment:
      - DB_USER=${MYSQL_ADDON_USER}
      - DB_PASS=${MYSQL_ADDON_PASSWORD}
      - DB_HOST=${MYSQL_ADDON_HOST}
      - DB_PORT=${MYSQL_ADDON_PORT}
      - DB_NAME=${MYSQL_ADDON_DB}
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: round-strike-db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: roundstrike_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # Uncomment the following section to enable the frontend service
  # Note: Need to solve hot reload issue before enabling frontend with Docker.
  # frontend:
  #   build:
  #     context: ./frontend
  #   container_name: round-strike-frontend
  #   working_dir: /app
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development
  #   command: npm run dev
  #   depends_on:
  #     - backend

volumes:
  mysql-data:
