services:
  backend:
    build:
      context: ./backend
    container_name: round-strike-backend
    volumes:
      - ./backend:/app
    ports:
      - "3002:3002"
    environment:
     - DB_USER=${DB_USER}
     - DB_PASS=${DB_PASS}
     - DB_HOST=${DB_HOST}
     - DB_PORT=${DB_PORT}
     - DB_NAME=${DB_NAME}
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: round-strike-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: roundstrike_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
