# .air.toml

# Root path of the application
root = "."

# Temporary directory for the compiled binaries
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd"
  bin = "tmp/main"
  full_bin = "tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]
  poll = true

[log]
  level = "debug"         # Log level set to debug for detailed logging
